version: "3"

services:
  
  apigateway:
    image: apigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "5005:80"
    depends_on:
      - supportticketwebapi
  
  supportticketwebapi:
    image: supportticketwebapi
    container_name: supportticketwebapi
    build:
      context: .
      dockerfile: SupportTicketWebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
    depends_on:
      - postgresdb
  
  postgresdb:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb: